all: presentacion

presentacion: presentacion.tex
	pdflatex presentacion.tex

clean:
	-rm *~
	-rm *.aux
	-rm *.log
	-rm *.out
	-rm *.toc
	-rm *.bbl
	-rm *.blg
	-rm *.glo
	-rm *.idx
	-rm *.ilg
	-rm *.ind
	-rm *.lof
	-rm *.lot
	-rm *.nlo
	-rm presentacion.pdf
